#!/usr/bin/env python3
"""
adapter: nginx_collect
Auto-generated by skg.forge. Review collection commands and check functions.
Generated: 2026-03-14T23:24:22.404919+00:00
"""
import json, uuid, re
from pathlib import Path
from datetime import datetime, timezone

TOOLCHAIN = "skg-nginx-toolchain"
SOURCE_ID = "adapter.nginx_collect"


def get_version():
    try:
        return (Path(__file__).resolve().parents[2] / "VERSION").read_text().strip()
    except Exception:
        return "0.0.0"


def iso_now():
    return datetime.now(timezone.utc).isoformat()


def emit(out_path, wicket_id, status, evidence_rank,
         evidence_source_kind, pointer, confidence,
         attack_path_id, run_id, workload_id, extra_payload=None):
    """Append one obs.attack.precondition event to NDJSON file."""
    from datetime import datetime, timezone
    import json, uuid
    now = datetime.now(timezone.utc).isoformat()
    event = {
        "id": str(uuid.uuid4()), "ts": now,
        "type": "obs.attack.precondition",
        "source": {"source_id": SOURCE_ID, "toolchain": TOOLCHAIN,
                   "version": get_version()},
        "payload": {"wicket_id": wicket_id, "status": status,
                    "attack_path_id": attack_path_id, "run_id": run_id,
                    "workload_id": workload_id, **(extra_payload or {})},
        "provenance": {"evidence_rank": evidence_rank,
                       "evidence": {"source_kind": evidence_source_kind,
                                    "pointer": pointer,
                                    "collected_at": now,
                                    "confidence": confidence}},
    }
    with open(out_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(event) + "\n")



def _run(ssh, cmd: str, timeout: int = 10) -> str:
    """Execute command over SSH, return stdout."""
    try:
        _, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
        return stdout.read().decode("utf-8", errors="replace").strip()
    except Exception as exc:
        return f"ERROR: {exc}"



def check_n_01(collection, out, attack_path_id, run_id, workload_id):
    """Check N-01: nginx service is reachable from attacker position"""
    # Evidence hint: Network connectivity to nginx port confirmed
    # TODO: parse collection data for this condition
    # Collection keys available: ['ss', 'ps', 'find']
    evidence = collection.get("nginx_reachable", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "N-01", status,
         evidence_rank=4, evidence_source_kind="ssh_collection",
         pointer="Network connectivity to nginx port confi",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": evidence[:200] if evidence else "not collected"})

def check_n_02(collection, out, attack_path_id, run_id, workload_id):
    """Check N-02: nginx service accepts unauthenticated connections"""
    # Evidence hint: Connect without credentials and observe response
    # TODO: parse collection data for this condition
    # Collection keys available: ['ss', 'ps', 'find']
    evidence = collection.get("nginx_no_auth", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "N-02", status,
         evidence_rank=1, evidence_source_kind="ssh_collection",
         pointer="Connect without credentials and observe ",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": evidence[:200] if evidence else "not collected"})

def check_n_03(collection, out, attack_path_id, run_id, workload_id):
    """Check N-03: nginx service uses default or weak credentials"""
    # Evidence hint: Attempt authentication with known default credentials
    # TODO: parse collection data for this condition
    # Collection keys available: ['ss', 'ps', 'find']
    evidence = collection.get("nginx_default_creds", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "N-03", status,
         evidence_rank=1, evidence_source_kind="ssh_collection",
         pointer="Attempt authentication with known defaul",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": evidence[:200] if evidence else "not collected"})

def check_n_04(collection, out, attack_path_id, run_id, workload_id):
    """Check N-04: nginx configuration file is readable"""
    # Evidence hint: Read nginx config file for auth/binding settings
    # TODO: parse collection data for this condition
    # Collection keys available: ['ss', 'ps', 'find']
    evidence = collection.get("nginx_config_exposed", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "N-04", status,
         evidence_rank=3, evidence_source_kind="ssh_collection",
         pointer="Read nginx config file for auth/binding ",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": evidence[:200] if evidence else "not collected"})


def run_checks(collection, out, attack_path_id, run_id, workload_id):
    """Run all check functions against collected data."""
    check_n_01(collection, out, attack_path_id, run_id, workload_id)
    check_n_02(collection, out, attack_path_id, run_id, workload_id)
    check_n_03(collection, out, attack_path_id, run_id, workload_id)
    check_n_04(collection, out, attack_path_id, run_id, workload_id)


def main():
    import argparse, paramiko
    p = argparse.ArgumentParser()
    p.add_argument("--host", required=True)
    p.add_argument("--user", required=True)
    p.add_argument("--password", default=None)
    p.add_argument("--key", default=None)
    p.add_argument("--out", required=True)
    p.add_argument("--attack-path-id", required=True)
    p.add_argument("--workload-id", default=None)
    p.add_argument("--run-id", default=None)
    a = p.parse_args()

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    connect_kw = {"hostname": a.host, "username": a.user, "timeout": 15}
    if a.key:
        connect_kw["key_filename"] = a.key
    elif a.password:
        connect_kw["password"] = a.password
    ssh.connect(**connect_kw)

    collection = {}
    collection["ss"] = _run(ssh, 'ss -tnlp | grep nginx')
    collection["ps"] = _run(ssh, 'ps aux | grep nginx')
    collection["find"] = _run(ssh, "find /etc -name '*nginx*' -type f 2>/dev/null | head -5")

    run_id = a.run_id or str(uuid.uuid4())
    wid = a.workload_id or a.host
    out = Path(a.out)
    run_checks(collection, out, a.attack_path_id, run_id, wid)
    ssh.close()


if __name__ == "__main__":
    main()
