#!/usr/bin/env python3
"""
adapter: web_collect
Auto-generated by skg.forge. Review collection commands and check functions.
Generated: 2026-03-16T18:21:03.954537+00:00
"""
import json, uuid, re
from pathlib import Path
from datetime import datetime, timezone

TOOLCHAIN = "skg-web-toolchain"
SOURCE_ID = "adapter.web_collect"


def get_version():
    try:
        return (Path(__file__).resolve().parents[2] / "VERSION").read_text().strip()
    except Exception:
        return "0.0.0"


def iso_now():
    return datetime.now(timezone.utc).isoformat()


def emit(out_path, wicket_id, status, evidence_rank,
         evidence_source_kind, pointer, confidence,
         attack_path_id, run_id, workload_id, extra_payload=None):
    """Append one obs.attack.precondition event to NDJSON file."""
    from datetime import datetime, timezone
    import json, uuid
    now = datetime.now(timezone.utc).isoformat()
    event = {
        "id": str(uuid.uuid4()), "ts": now,
        "type": "obs.attack.precondition",
        "source": {"source_id": SOURCE_ID, "toolchain": TOOLCHAIN,
                   "version": get_version()},
        "payload": {"wicket_id": wicket_id, "status": status,
                    "attack_path_id": attack_path_id, "run_id": run_id,
                    "workload_id": workload_id, **(extra_payload or {})},
        "provenance": {"evidence_rank": evidence_rank,
                       "evidence": {"source_kind": evidence_source_kind,
                                    "pointer": pointer,
                                    "collected_at": now,
                                    "confidence": confidence}},
    }
    with open(out_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(event) + "\n")



def _run(ssh, cmd: str, timeout: int = 10) -> str:
    """Execute command over SSH, return stdout."""
    try:
        _, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
        return stdout.read().decode("utf-8", errors="replace").strip()
    except Exception as exc:
        return f"ERROR: {exc}"



def check_w_01(collection, out, attack_path_id, run_id, workload_id):
    """Check W-01: Target system or service responds to network probes; collect"""
    # Evidence hint: TCP connect or ICMP probe confirms reachability; confirm via port scan or HTTP HEAD request
    # TODO: parse collection data for this condition
    # Collection keys available: ['nvd_feed::cve_2007_4723']
    evidence = collection.get("target_reachable_and_responsive", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "W-01", status,
         evidence_rank=2, evidence_source_kind="ssh_collection",
         pointer="TCP connect or ICMP probe confirms reach",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": evidence[:200] if evidence else "not collected"})

def check_w_02(collection, out, attack_path_id, run_id, workload_id):
    """Check W-02: Target service is listening on a reachable port and acceptin"""
    # Evidence hint: Service banner grab or HTTP 200/401 response confirms service is listening
    # TODO: parse collection data for this condition
    # Collection keys available: ['nvd_feed::cve_2007_4723']
    evidence = collection.get("target_service_exposed", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "W-02", status,
         evidence_rank=2, evidence_source_kind="ssh_collection",
         pointer="Service banner grab or HTTP 200/401 resp",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": evidence[:200] if evidence else "not collected"})

def check_w_03(collection, out, attack_path_id, run_id, workload_id):
    """Check W-03: ScriptAlias directory in NCSA and Apache httpd allowed attac"""
    # Evidence hint: Network-accessible service probe; confirm reachability via TCP connect or banner grab
    # TODO: parse collection data for this condition
    # Collection keys available: ['nvd_feed::cve_2007_4723']
    evidence = collection.get("apache_high_vuln_present", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "W-03", status,
         evidence_rank=2, evidence_source_kind="ssh_collection",
         pointer="Network-accessible service probe; confir",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": evidence[:200] if evidence else "not collected"})


def run_checks(collection, out, attack_path_id, run_id, workload_id):
    """Run all check functions against collected data."""
    check_w_01(collection, out, attack_path_id, run_id, workload_id)
    check_w_02(collection, out, attack_path_id, run_id, workload_id)
    check_w_03(collection, out, attack_path_id, run_id, workload_id)


def main():
    import argparse, paramiko
    p = argparse.ArgumentParser()
    p.add_argument("--host", required=True)
    p.add_argument("--user", required=True)
    p.add_argument("--password", default=None)
    p.add_argument("--key", default=None)
    p.add_argument("--out", required=True)
    p.add_argument("--attack-path-id", required=True)
    p.add_argument("--workload-id", default=None)
    p.add_argument("--run-id", default=None)
    a = p.parse_args()

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    connect_kw = {"hostname": a.host, "username": a.user, "timeout": 15}
    if a.key:
        connect_kw["key_filename"] = a.key
    elif a.password:
        connect_kw["password"] = a.password
    ssh.connect(**connect_kw)

    collection = {}
    collection["nvd_feed__cve_2007_4"] = _run(ssh, 'nvd_feed::CVE-2007-4723')

    run_id = a.run_id or str(uuid.uuid4())
    wid = a.workload_id or a.host
    out = Path(a.out)
    run_checks(collection, out, a.attack_path_id, run_id, wid)
    ssh.close()


if __name__ == "__main__":
    main()
