"""
skg.forge.generator
====================
Toolchain generator — takes a gap candidate and produces a complete,
runnable toolchain directory.

Output structure:
  skg-{domain}-toolchain/
    VERSION
    contracts/catalogs/attack_preconditions_catalog.{domain}.v1.json
    adapters/ssh_collect/
      __init__.py
      parse.py          ← generated: collection commands + check functions
    projections/{domain}/
      run.py            ← generated from boilerplate template

The catalog is generated by the resonance engine + generation backend
(ollama or Anthropic API). The adapter is generated by the same backend
grounded in existing adapter patterns. The projector is pure boilerplate
— the domain name is the only variable.

The generator does NOT install the toolchain. It writes to a staging
directory. The proposal system presents it to the operator, who accepts
or rejects. Acceptance calls install().
"""
from __future__ import annotations

import json
import logging
import os
import re
import shutil
import textwrap
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from skg_core.config.paths import SKG_HOME
from skg_services.gravity.path_policy import FORGE_STAGING

log = logging.getLogger("skg.forge.generator")

# Post-install hooks: callables invoked with (installed_path: Path) after
# every successful toolchain install. Register via append().
# gravity_field.py uses this to re-register wicket wavelengths so that
# formerly dark hypotheses become observable after a new toolchain lands.
_post_install_hooks: list = []

# ---------------------------------------------------------------------------
# Projector boilerplate template — pure boilerplate, domain name only variable
# ---------------------------------------------------------------------------

PROJECTOR_TEMPLATE = '''\
#!/usr/bin/env python3
"""
projections/{domain}/run.py
============================
Auto-generated projection engine for the {domain_label} toolchain.
Same substrate logic as all SKG projectors: tri-state, score, classify.

Generated by skg.forge at {generated_at}
"""

import argparse, json, uuid
from datetime import datetime, timezone
from pathlib import Path


TOOLCHAIN  = "skg-{domain}-toolchain"
SOURCE_ID  = "projection.{domain}"
SCORE_KEY  = "{domain}_score"


def get_version() -> str:
    try:
        return Path(__file__).resolve().parents[2].joinpath("VERSION").read_text().strip()
    except Exception:
        return "0.0.0"


def iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def compute_{safe_domain}(events, catalog: dict, attack_path_id: str,
                           run_id: str = None, workload_id: str = None) -> dict:
    """In-process projection — called by skg.sensors.projector."""
    paths = catalog.get("attack_paths", {{}})
    ap = paths.get(attack_path_id)
    if not ap:
        return {{}}
    required = ap.get("required_wickets", [])

    latest: dict[str, str] = {{}}
    latest_ts: dict[str, str] = {{}}
    for ev in events:
        if ev.get("type") != "obs.attack.precondition":
            continue
        payload = ev.get("payload", {{}})
        wid = payload.get("wicket_id")
        ts  = ev.get("ts", "")
        if wid in required:
            if wid not in latest_ts or ts > latest_ts[wid]:
                latest[wid]    = payload.get("status", "unknown")
                latest_ts[wid] = ts

    realized = [w for w in required if latest.get(w) == "realized"]
    blocked  = [w for w in required if latest.get(w) == "blocked"]
    unknown  = [w for w in required if latest.get(w, "unknown") == "unknown"]

    if blocked:
        classification = "not_realized"
    elif unknown:
        classification = "indeterminate"
    else:
        classification = "realized"

    score = len(realized) / len(required) if required else 0.0
    run_id = run_id or str(uuid.uuid4())

    return {{
        "id":             str(uuid.uuid4()),
        "ts":             iso_now(),
        "type":           "interp.attack.path",
        "source": {{
            "source_id":  SOURCE_ID,
            "toolchain":  TOOLCHAIN,
            "version":    get_version(),
        }},
        "payload": {{
            "attack_path_id":  attack_path_id,
            "workload_id":     workload_id or "unknown",
            "run_id":          run_id,
            "classification":  classification,
            SCORE_KEY:         round(score, 4),
            "required_wickets": required,
            "realized":        realized,
            "blocked":         blocked,
            "unknown":         unknown,
            "latest_status":   latest,
            "computed_at":     iso_now(),
        }},
    }}


def main():
    p = argparse.ArgumentParser(description="{domain_label} projection engine")
    p.add_argument("--in",  dest="infile",  required=True)
    p.add_argument("--out", dest="outfile", required=True)
    p.add_argument("--attack-path-id", required=True)
    p.add_argument("--workload-id",    default=None)
    p.add_argument("--run-id",         default=None)
    a = p.parse_args()

    catalog_dir = Path(__file__).resolve().parents[2] / "contracts" / "catalogs"
    catalogs = list(catalog_dir.glob("*.json"))
    if not catalogs:
        raise SystemExit("No catalog found")
    catalog = json.loads(catalogs[0].read_text())

    events = []
    with open(a.infile) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    events.append(json.loads(line))
                except Exception:
                    pass

    result = compute_{safe_domain}(events, catalog, a.attack_path_id,
                                    run_id=a.run_id, workload_id=a.workload_id)
    if result:
        Path(a.outfile).write_text(json.dumps(result, indent=2))
    else:
        raise SystemExit(f"Unknown attack_path_id: {{a.attack_path_id}}")


if __name__ == "__main__":
    main()
'''

# ---------------------------------------------------------------------------
# Adapter generation prompt
# ---------------------------------------------------------------------------

def _build_adapter_prompt(domain: str, description: str, catalog: dict,
                           gap: dict, resonance_context: dict,
                           example_adapters: list[str]) -> str:
    """
    Build the adapter generation prompt.
    Grounded in existing adapter patterns — the model translates, not invents.
    """
    wickets = catalog.get("wickets", {})
    attack_paths = catalog.get("attack_paths", {})
    collection_hints = gap.get("collection_hints", [])
    prefix = next(iter(wickets), f"{domain[:2].upper()}-01")[:2] if wickets else domain[:2].upper()

    wicket_list = "\n".join(
        f"  {wid}: {w.get('label','')} — {w.get('description','')} "
        f"(rank {w.get('default_rank',2)}, hint: {w.get('evidence_hint','')})"
        for wid, w in list(wickets.items())[:15]
    )

    path_list = "\n".join(
        f"  {pid}: requires {v.get('required_wickets', [])}"
        for pid, v in list(attack_paths.items())[:3]
    )

    hints_str = "\n".join(f"  {h}" for h in collection_hints[:8])

    # Trim example adapters to fit prompt
    examples_str = ""
    for i, ex in enumerate(example_adapters[:2], 1):
        trimmed = ex[:2000] if len(ex) > 2000 else ex
        examples_str += f"\n--- EXAMPLE ADAPTER {i} ---\n{trimmed}\n"

    return f"""You are a Python code generator. Generate a complete, FULLY IMPLEMENTED SKG adapter parse.py for the {domain} toolchain.

DOMAIN: {domain}
DESCRIPTION: {description}
ATTACK SURFACE: {gap.get('attack_surface', '')}

WICKETS TO COVER:
{wicket_list}

ATTACK PATHS:
{path_list}

COLLECTION COMMANDS (SSH — run on target host):
{hints_str}

EXISTING ADAPTER EXAMPLES (follow this exact pattern):
{examples_str}

RULES:
1. File starts with: TOOLCHAIN = "skg-{domain}-toolchain" / SOURCE_ID = "adapter.{domain}_collect"
2. Each wicket gets one check_WICKETID() function that:
   - Takes: (collection_data: dict, out: Path, attack_path_id: str, run_id: str, workload_id: str)
   - Calls emit() with status "realized", "blocked", or "unknown"
   - Uses the collection_data dict keys matching the collection commands
3. emit() signature: emit(out, wicket_id, status, evidence_rank, evidence_source_kind, pointer, confidence, attack_path_id, run_id, workload_id, extra_payload=None)
4. collection_data keys: use snake_case versions of the collection commands (e.g. "redis_ping", "redis_config", "service_status")
5. main() runs collection commands via SSH using paramiko (see example), writes to out
6. Include a run_checks(collection_data, out, attack_path_id, run_id, workload_id) function that calls all check_ functions
7. Status logic:
   - "realized" = condition confirmed, vulnerability present
   - "blocked" = condition confirmed absent (control in place)
   - "unknown" = insufficient evidence to determine

CRITICAL — FUNCTIONAL CHECK LOGIC REQUIRED:
- Every check_WICKETID() function MUST implement real parsing logic based on the evidence_hint
- NEVER write: status = "unknown"  # Replace with ...
- NEVER write: # TODO
- NEVER have both branches of an if/else return the same status
- Each check function must do ONE of:
  a) Parse a version string and compare (e.g. version < (2,4,0) → "realized", else "blocked")
  b) Search for a string pattern (e.g. "NOPASSWD" in sudo_output → "realized")
  c) Check if output is non-empty and non-error (e.g. key_file exists → "realized")
  d) Check OS/platform type (e.g. "solaris" in uname → relevant, else "blocked")
  e) Check for presence of a process/service (e.g. "docker" in ps_output → "realized")

EXAMPLE of good check function:
def check_XY_01(collection, out, attack_path_id, run_id, workload_id):
    ssh_output = collection.get("ssh_banner", "")
    # OpenSSH < 8.0 allows some deprecated key types
    m = re.search(r'OpenSSH_(\\d+)\\.(\\d+)', ssh_output or "")
    if m:
        ver = (int(m.group(1)), int(m.group(2)))
        if ver < (8, 0):
            status, conf = "realized", 0.85
        else:
            status, conf = "blocked", 0.85
    else:
        status, conf = "unknown", 0.5
    emit(out, "XY-01", status, 3, "ssh_collection", "OpenSSH version from banner", conf,
         attack_path_id, run_id, workload_id, {{"detail": ssh_output[:100]}})

COLLECTION COMMAND DESIGN: The main() function must run real SSH commands that produce parseable output. Use commands like:
- Version checks: "apache2 -v 2>/dev/null || httpd -v 2>/dev/null || echo not_found"
- Service status: "systemctl is-active servicename 2>/dev/null || echo not_found"
- File/permission checks: "ls -la /path/to/file 2>/dev/null || echo not_found"
- Process presence: "ps aux | grep -i processname | grep -v grep || echo not_found"
- Package version: "dpkg -l packagename 2>/dev/null | awk '/^ii/{{print $3}}' || echo not_found"

OUTPUT: Only the complete Python file. No markdown, no explanation. No TODO comments. No placeholder status values."""


# ---------------------------------------------------------------------------
# Adapter post-processing — validate and fix common generation issues
# ---------------------------------------------------------------------------

def _check_adapter_quality(code: str, domain: str) -> tuple[bool, list[str]]:
    """
    Detect placeholder patterns that indicate the adapter is not functional.
    Returns (is_acceptable, list_of_issues).
    """
    issues = []
    lines = code.splitlines()

    # Count TODO lines and stub patterns
    todo_lines = [i+1 for i, l in enumerate(lines)
                  if "# TODO" in l or "# todo" in l.lower()]
    stub_lines = [i+1 for i, l in enumerate(lines)
                  if ("Replace with" in l or "Replace With" in l)
                  and ("unknown" in l or "realized" in l or "blocked" in l)]

    # Check: both branches of if/else returning "unknown"
    same_branch_stubs = 0
    for i in range(len(lines) - 2):
        l_stripped = lines[i].replace(" ", "").replace('"', "'")
        if "status='unknown'" in l_stripped:
            for j in range(i+1, min(i+4, len(lines))):
                lj_stripped = lines[j].replace(" ", "").replace('"', "'")
                if "status='unknown'" in lj_stripped:
                    same_branch_stubs += 1
                    break

    if todo_lines:
        issues.append(f"TODO markers at lines {todo_lines[:5]}")
    if stub_lines:
        issues.append(f"Placeholder 'Replace with' comments at lines {stub_lines[:5]}")
    if same_branch_stubs >= 2:
        issues.append(f"Both if/else branches return 'unknown' in {same_branch_stubs} check functions — no real parsing logic")

    is_acceptable = len(issues) == 0
    return is_acceptable, issues


def _fix_adapter(code: str, domain: str, catalog: dict) -> str:
    """Fix common generation issues in adapter code."""
    # Ensure TOOLCHAIN and SOURCE_ID are correct
    tc = f'skg-{domain}-toolchain'
    sid = f'adapter.{domain}_collect'

    if f'TOOLCHAIN = "skg-' not in code and 'TOOLCHAIN' not in code:
        code = f'TOOLCHAIN = "{tc}"\nSOURCE_ID = "{sid}"\n\n' + code
    else:
        # Fix any wrong toolchain name
        code = re.sub(r'TOOLCHAIN\s*=\s*"[^"]*"', f'TOOLCHAIN = "{tc}"', code)
        code = re.sub(r'SOURCE_ID\s*=\s*"[^"]*"', f'SOURCE_ID = "{sid}"', code)

    # Ensure emit function is present — copy from template if missing
    if 'def emit(' not in code:
        code = _EMIT_TEMPLATE + '\n\n' + code

    # Ensure iso_now is present
    if 'def iso_now' not in code:
        code = 'def iso_now():\n    from datetime import datetime, timezone\n    return datetime.now(timezone.utc).isoformat()\n\n' + code

    # Ensure get_version is present
    if 'def get_version' not in code:
        code = ('def get_version():\n    try:\n'
                '        return (Path(__file__).resolve().parents[2] / "VERSION").read_text().strip()\n'
                '    except Exception:\n        return "0.0.0"\n\n') + code

    # Ensure imports
    needed_imports = ['import json', 'import uuid', 'from pathlib import Path',
                      'from datetime import datetime, timezone']
    existing = code[:500]
    prepend = ''
    for imp in needed_imports:
        if imp not in existing:
            prepend += imp + '\n'
    if prepend:
        code = prepend + '\n' + code

    return code


_EMIT_TEMPLATE = '''def emit(out_path, wicket_id, status, evidence_rank,
         evidence_source_kind, pointer, confidence,
         attack_path_id, run_id, workload_id, extra_payload=None):
    """Append one obs.attack.precondition event to NDJSON file."""
    from datetime import datetime, timezone
    import json, uuid
    now = datetime.now(timezone.utc).isoformat()
    event = {
        "id": str(uuid.uuid4()), "ts": now,
        "type": "obs.attack.precondition",
        "source": {"source_id": SOURCE_ID, "toolchain": TOOLCHAIN,
                   "version": get_version()},
        "payload": {"wicket_id": wicket_id, "status": status,
                    "attack_path_id": attack_path_id, "run_id": run_id,
                    "workload_id": workload_id, **(extra_payload or {})},
        "provenance": {"evidence_rank": evidence_rank,
                       "evidence": {"source_kind": evidence_source_kind,
                                    "pointer": pointer,
                                    "collected_at": now,
                                    "confidence": confidence}},
    }
    with open(out_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(event) + "\\n")
'''


# ---------------------------------------------------------------------------
# Example adapter loader — grounding context for generation
# ---------------------------------------------------------------------------

def _load_example_adapters(n: int = 2) -> list[str]:
    """Load N existing adapter parse.py files as generation examples."""
    examples = []
    for tc_dir in sorted(SKG_HOME.glob("skg-*-toolchain")):
        for parse_py in tc_dir.glob("adapters/*/parse.py"):
            try:
                text = parse_py.read_text(errors="replace")
                if len(text) > 200:
                    examples.append(text)
                    if len(examples) >= n:
                        return examples
            except Exception:
                pass
    return examples


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

def generate_toolchain(
    domain: str,
    description: str,
    gap: dict,
    resonance_engine=None,
    staging_dir: Path | None = None,
    force: bool = False,
) -> dict:
    """
    Generate a complete toolchain for the given domain.

    Returns:
      {
        success: bool,
        domain: str,
        staging_path: str,
        catalog: dict,
        wicket_count: int,
        path_count: int,
        files_written: [str],
        errors: [str],
      }
    """
    staging_dir = staging_dir or FORGE_STAGING
    tc_name = f"skg-{domain}-toolchain"
    out_dir = staging_dir / tc_name

    if out_dir.exists() and not force:
        log.info(f"[forge] staging dir exists: {out_dir} (use force=True to regenerate)")
        return {
            "success": True, "domain": domain,
            "staging_path": str(out_dir),
            "already_existed": True,
        }

    if out_dir.exists():
        shutil.rmtree(out_dir)

    errors = []
    files_written = []

    # ----- Step 1: Generate catalog ----------------------------------------
    log.info(f"[forge] generating catalog for: {domain}")
    catalog = None
    generation_backend = None

    if resonance_engine:
        query = f"{domain}: {description} {gap.get('attack_surface','')}"
        context = resonance_engine.surface(query, k_each=4)
    else:
        context = {"wickets": [], "adapters": [], "domains": []}

    # Deterministic-first path: if the gap carries compiler hints from a fold or
    # gap detector, try to derive the catalog from CVE/NVD data before asking a
    # model to synthesize it.
    compiler_hints = gap.get("compiler_hints") or {}
    if compiler_hints:
        try:
            from skg.forge.compiler import compile_catalog
            compiled = compile_catalog(
                domain=domain,
                description=description,
                packages=list(compiler_hints.get("packages") or []),
                keywords=list(compiler_hints.get("keywords") or []),
                prefix=compiler_hints.get("prefix"),
                api_key=compiler_hints.get("api_key"),
                min_cvss=float(compiler_hints.get("min_cvss", 4.0)),
                max_wickets=int(compiler_hints.get("max_wickets", 20)),
            )
            if compiled and compiled.get("wickets"):
                catalog = compiled
                generation_backend = "compiler"
        except Exception as exc:
            errors.append(f"Compiler catalog generation failed: {exc}")

    # Try ollama first, then Anthropic API
    if catalog is None:
        try:
            from skg.resonance.ollama_backend import OllamaBackend
            backend = OllamaBackend()
            if backend.available():
                catalog, cat_errors = backend.draft_catalog(domain, description, context)
                errors.extend(cat_errors)
                generation_backend = f"ollama:{backend.model()}"
        except Exception as exc:
            log.debug(f"[forge] ollama unavailable: {exc}")

    if catalog is None:
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if api_key:
            try:
                from skg.resonance.drafter import draft_catalog
                # Build a minimal engine wrapper if needed
                class _MinEngine:
                    def surface(self, q, k_each=4): return context
                    def save_draft(self, d, c): return Path("/tmp") / f"{d}_draft.json"
                result = draft_catalog(_MinEngine(), domain, description, api_key=api_key)
                catalog = result["catalog"]
                errors.extend(result.get("validation_errors", []))
                generation_backend = "anthropic"
            except Exception as exc:
                errors.append(f"API catalog generation failed: {exc}")

    if catalog is None:
        # Last resort: generate a minimal catalog structure from the gap data
        catalog = _generate_minimal_catalog(domain, description, gap)
        generation_backend = "template"
        errors.append("Used template catalog — no generation backend available")

    # ----- Step 2: Generate adapter ----------------------------------------
    log.info(f"[forge] generating adapter for: {domain}")
    adapter_code = None
    example_adapters = _load_example_adapters(2)

    adapter_prompt = _build_adapter_prompt(
        domain, description, catalog, gap, context, example_adapters
    )

    if generation_backend and "ollama" in generation_backend:
        try:
            from skg.resonance.ollama_backend import OllamaBackend
            backend = OllamaBackend()
            raw = backend.generate(adapter_prompt, num_predict=1024)
            raw = re.sub(r'^```python\s*', '', raw)
            raw = re.sub(r'^```\s*', '', raw)
            raw = re.sub(r'\s*```$', '', raw).strip()
            if len(raw) > 200 and 'def ' in raw:
                adapter_code = _fix_adapter(raw, domain, catalog)
        except Exception as exc:
            errors.append(f"Adapter generation failed: {exc}")

    if adapter_code is None and os.environ.get("ANTHROPIC_API_KEY"):
        try:
            adapter_code = _generate_adapter_via_api(
                adapter_prompt, os.environ["ANTHROPIC_API_KEY"]
            )
            adapter_code = _fix_adapter(adapter_code, domain, catalog)
        except Exception as exc:
            errors.append(f"API adapter generation failed: {exc}")

    if adapter_code is None:
        adapter_code = _generate_template_adapter(domain, catalog, gap)
        errors.append("Used template adapter — check collection commands")

    # Quality gate: detect stub/TODO patterns — HARD REJECT.
    # A stub adapter is worse than no adapter: it silently produces wrong
    # wicket states that corrupt field inference.  If the LLM returned a stub,
    # retry once with an explicit anti-stub reinforcement prompt; if the retry
    # also fails, return an error result so the proposal is never staged.
    if adapter_code:
        _ok, _issues = _check_adapter_quality(adapter_code, domain)
        if not _ok:
            log.warning("[forge] adapter quality gate FAIL for %s — retrying with anti-stub prompt: %s",
                        domain, _issues)
            # One retry with stub rejection injected into prompt
            _retry_code = None
            try:
                _stub_hint = (
                    "\n\nPREVIOUS ATTEMPT WAS REJECTED by the quality gate.\n"
                    f"Issues found: {'; '.join(_issues)}\n"
                    "You MUST NOT use TODO, pass, raise NotImplementedError, or placeholder comments.\n"
                    "Every check function must contain real conditional logic that reads from `collection`.\n"
                )
                _retry_prompt = adapter_prompt + _stub_hint
                if generation_backend and "ollama" in generation_backend:
                    from skg.resonance.ollama_backend import OllamaBackend
                    _ob = OllamaBackend()
                    _rraw = _ob.generate(_retry_prompt, num_predict=1024)
                    _rraw = re.sub(r'^```python\s*', '', _rraw)
                    _rraw = re.sub(r'^```\s*', '', _rraw)
                    _rraw = re.sub(r'\s*```$', '', _rraw).strip()
                    if len(_rraw) > 200 and 'def ' in _rraw:
                        _retry_code = _fix_adapter(_rraw, domain, catalog)
                elif os.environ.get("ANTHROPIC_API_KEY"):
                    _rraw2 = _generate_adapter_via_api(_retry_prompt, os.environ["ANTHROPIC_API_KEY"])
                    _retry_code = _fix_adapter(_rraw2, domain, catalog)
            except Exception as _re:
                log.debug("[forge] adapter retry exception: %s", _re)

            if _retry_code:
                _ok2, _issues2 = _check_adapter_quality(_retry_code, domain)
                if _ok2:
                    adapter_code = _retry_code
                    log.info("[forge] adapter retry passed quality gate for %s", domain)
                else:
                    log.error("[forge] adapter retry still failed quality gate for %s: %s", domain, _issues2)
                    errors.extend([f"adapter_quality_hard_fail: {i}" for i in _issues2])
                    return {
                        "id": proposal_id,
                        "domain": domain,
                        "status": "error",
                        "error": "adapter quality gate: stub adapter after retry — not staged",
                        "quality_issues": _issues2,
                        "files_written": [],
                    }
            else:
                errors.extend([f"adapter_quality_hard_fail: {i}" for i in _issues])
                return {
                    "id": proposal_id,
                    "domain": domain,
                    "status": "error",
                    "error": "adapter quality gate: stub adapter, retry unavailable — not staged",
                    "quality_issues": _issues,
                    "files_written": [],
                }

    # ----- Step 3: Write toolchain directory structure ---------------------
    log.info(f"[forge] writing toolchain to: {out_dir}")

    try:
        # Directory structure
        (out_dir / "contracts" / "catalogs").mkdir(parents=True)
        (out_dir / "adapters" / "ssh_collect").mkdir(parents=True)
        (out_dir / "projections" / domain).mkdir(parents=True)

        # VERSION
        vf = out_dir / "VERSION"
        vf.write_text("0.1.0-forge\n")
        files_written.append("VERSION")

        # Catalog
        cat_name = f"attack_preconditions_catalog.{domain}.v1.json"
        cat_path = out_dir / "contracts" / "catalogs" / cat_name
        cat_path.write_text(json.dumps(catalog, indent=2))
        files_written.append(f"contracts/catalogs/{cat_name}")

        # Adapter __init__.py
        init_path = out_dir / "adapters" / "ssh_collect" / "__init__.py"
        init_path.write_text("")
        files_written.append("adapters/ssh_collect/__init__.py")

        # Adapter parse.py
        adapter_path = out_dir / "adapters" / "ssh_collect" / "parse.py"
        adapter_path.write_text(adapter_code)
        files_written.append("adapters/ssh_collect/parse.py")

        # Projector __init__.py
        proj_init = out_dir / "projections" / domain / "__init__.py"
        proj_init.write_text("")
        files_written.append(f"projections/{domain}/__init__.py")

        # Projector run.py — boilerplate template
        safe_domain = domain.replace("-", "_")
        projector_code = PROJECTOR_TEMPLATE.format(
            domain=domain,
            safe_domain=safe_domain,
            domain_label=domain.replace("_", " ").replace("-", " ").title(),
            generated_at=datetime.now(timezone.utc).isoformat(),
        )
        proj_path = out_dir / "projections" / domain / "run.py"
        proj_path.write_text(projector_code)
        files_written.append(f"projections/{domain}/run.py")

        # Forge metadata
        meta = {
            "domain": domain,
            "description": description,
            "attack_surface": gap.get("attack_surface", ""),
            "hosts": gap.get("hosts", []),
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generation_backend": generation_backend,
            "errors": errors,
        }
        (out_dir / "forge_meta.json").write_text(json.dumps(meta, indent=2))
        files_written.append("forge_meta.json")

    except Exception as exc:
        errors.append(f"File write error: {exc}")
        return {"success": False, "domain": domain, "errors": errors}

    return {
        "success": True,
        "domain": domain,
        "tc_name": tc_name,
        "staging_path": str(out_dir),
        "catalog": catalog,
        "wicket_count": len(catalog.get("wickets", {})),
        "path_count": len(catalog.get("attack_paths", {})),
        "files_written": files_written,
        "generation_backend": generation_backend,
        "errors": errors,
    }


def install_toolchain(staging_path: str | Path,
                      install_dir: Path | None = None) -> dict:
    """
    Install a staged toolchain into the main SKG directory.
    Returns installation metadata.
    """
    staging_path = Path(staging_path)
    install_dir = install_dir or SKG_HOME
    dest = install_dir / staging_path.name
    result = {
        "installed_path": str(dest),
        "installed": False,
        "preserved_existing": False,
    }

    staged_catalogs = list(staging_path.glob("contracts/catalogs/*.json"))
    existing_catalogs = list(dest.glob("contracts/catalogs/*.json")) if dest.exists() else []
    if staged_catalogs and existing_catalogs:
        try:
            staged = json.loads(staged_catalogs[0].read_text())
            existing = json.loads(existing_catalogs[0].read_text())
            staged_wickets = staged.get("wickets", {}) or {}
            existing_wickets = existing.get("wickets", {}) or {}
            staged_paths = staged.get("attack_paths", {}) or {}
            existing_paths = existing.get("attack_paths", {}) or {}

            staged_score = (len(staged_wickets), len(staged_paths))
            existing_score = (len(existing_wickets), len(existing_paths))
            has_new_ids = bool(
                set(staged_wickets) - set(existing_wickets)
                or set(staged_paths) - set(existing_paths)
            )

            # Refuse to overwrite a stronger active toolchain with a weaker
            # staged draft. Keep the accepted record, but preserve the active
            # runtime substrate until a non-regressive merge/install exists.
            if staged_score < existing_score and not has_new_ids:
                log.warning(
                    "[forge] refusing regressive install: %s weaker than %s",
                    staging_path, dest,
                )
                result["preserved_existing"] = True
                return result
        except Exception as exc:
            log.warning(f"[forge] install comparison failed: {exc}")

    if dest.exists():
        # Backup existing active tree before merging. Do not replace the whole
        # toolchain; staged forge output usually only contains generated
        # catalogs/projections and should not strip live adapters/runtime code.
        backup = dest.with_name(dest.name + ".backup")
        if backup.exists():
            shutil.rmtree(backup)
        shutil.copytree(dest, backup)
        shutil.copytree(staging_path, dest, dirs_exist_ok=True)
    else:
        shutil.copytree(staging_path, dest)
    log.info(f"[forge] installed: {dest}")
    result["installed"] = True

    # Install Python dependencies declared by the toolchain (if any).
    # Generated toolchains may emit a requirements.txt so they can pull in
    # domain-specific libraries (e.g. impacket for AD, paramiko for SSH).
    req_file = dest / "requirements.txt"
    if req_file.exists():
        try:
            import subprocess, sys
            proc = subprocess.run(
                [sys.executable, "-m", "pip", "install", "-r", str(req_file), "--quiet"],
                capture_output=True, text=True, timeout=120,
            )
            if proc.returncode == 0:
                log.info(f"[forge] dependencies installed from {req_file}")
            else:
                log.warning(f"[forge] pip install failed for {req_file}: {proc.stderr[:200]}")
        except Exception as exc:
            log.warning(f"[forge] dependency install error: {exc}")

    # Load through the shared projector discovery path so install-time
    # activation matches runtime activation.
    try:
        from skg_services.gravity.projector_runtime import (
            _discover_toolchain_projector,
            _projector_cache,
        )

        tc_name = staging_path.name
        _projector_cache.pop(tc_name, None)
        if _discover_toolchain_projector(tc_name):
            log.info(f"[forge] registered projector: {tc_name}")
        else:
            log.warning(f"[forge] projector discovery failed: {tc_name}")
    except Exception as exc:
        log.warning(f"[forge] projector registration failed: {exc}")

    # Notify registered post-install hooks (e.g. wicket graph re-registration).
    for _hook in list(_post_install_hooks):
        try:
            _hook(dest)
        except Exception as _he:
            log.debug(f"[forge] post-install hook error: {_he}")

    return result


# ---------------------------------------------------------------------------
# Template fallbacks — used when generation backend is unavailable
# ---------------------------------------------------------------------------

def _generate_minimal_catalog(domain: str, description: str, gap: dict) -> dict:
    """Generate a minimal catalog from gap data when no backend is available."""
    prefix = "".join(w[0].upper() for w in domain.split("_")[:3])[:3]
    hints = gap.get("collection_hints", [])
    surface = gap.get("attack_surface", "")
    
    # Parse attack surface description into wickets
    wickets = {}
    path_id = f"{domain}_initial_access_v1"
    
    # Always include connectivity
    wickets[f"{prefix}-01"] = {
        "label": f"{domain}_reachable",
        "description": f"{domain} service is reachable from attacker position",
        "evidence_hint": f"Network connectivity to {domain} port confirmed",
        "default_rank": 4
    }
    
    # Authentication condition
    wickets[f"{prefix}-02"] = {
        "label": f"{domain}_no_auth",
        "description": f"{domain} service accepts unauthenticated connections",
        "evidence_hint": f"Connect without credentials and observe response",
        "default_rank": 1
    }
    
    # Default/weak credentials
    wickets[f"{prefix}-03"] = {
        "label": f"{domain}_default_creds",
        "description": f"{domain} service uses default or weak credentials",
        "evidence_hint": f"Attempt authentication with known default credentials",
        "default_rank": 1
    }
    
    # Config exposure
    wickets[f"{prefix}-04"] = {
        "label": f"{domain}_config_exposed",
        "description": f"{domain} configuration file is readable",
        "evidence_hint": f"Read {domain} config file for auth/binding settings",
        "default_rank": 3
    }

    return {
        "domain": domain,
        "version": "0.1.0",
        "description": description,
        "wickets": wickets,
        "attack_paths": {
            path_id: {
                "label": f"{domain.replace('_',' ').title()} Initial Access",
                "description": f"Exploit {domain} service to gain initial access",
                "required_wickets": [f"{prefix}-01", f"{prefix}-02"],
                "ordered": False,
            }
        }
    }


def _generate_template_adapter(domain: str, catalog: dict, gap: dict) -> str:
    """Generate a minimal but functional adapter from templates."""
    hints = gap.get("collection_hints", [])
    wickets = catalog.get("wickets", {})
    tc = f"skg-{domain}-toolchain"
    sid = f"adapter.{domain}_collect"
    
    check_fns = []
    for wid, w in list(wickets.items())[:8]:
        fn_name = f"check_{wid.replace('-','_').lower()}"
        hint = w.get("evidence_hint", "")
        rank = w.get("default_rank", 2)
        label = w.get("label", wid)
        check_fns.append(f'''
def {fn_name}(collection, out, attack_path_id, run_id, workload_id):
    """Check {wid}: {w.get('description','')[:60]}"""
    # Evidence hint: {hint}
    # TODO: parse collection data for this condition
    # Collection keys available: {[h.split()[0].lower().replace('-','_') for h in hints[:4]]}
    evidence = collection.get("{label.replace('-','_')}", "")
    if evidence:
        status = "unknown"  # Replace with: "realized" or "blocked"
    else:
        status = "unknown"
    emit(out, "{wid}", status,
         evidence_rank={rank}, evidence_source_kind="ssh_collection",
         pointer="{hint[:40] if hint else label}",
         confidence=0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={{"detail": evidence[:200] if evidence else "not collected"}})
''')

    collection_cmds = []
    for h in hints[:8]:
        key = re.sub(r'[^a-z0-9_]', '_', h.split()[0].lower())[:20]
        collection_cmds.append(f'    collection["{key}"] = _run(ssh, {repr(h)})')

    all_checks = "\n    ".join(
        f'check_{wid.replace("-","_").lower()}(collection, out, attack_path_id, run_id, workload_id)'
        for wid in list(wickets.keys())[:8]
    )

    return f'''#!/usr/bin/env python3
"""
adapter: {domain}_collect
Auto-generated by skg.forge. Review collection commands and check functions.
Generated: {datetime.now(timezone.utc).isoformat()}
"""
import json, uuid, re
from pathlib import Path
from datetime import datetime, timezone

TOOLCHAIN = "{tc}"
SOURCE_ID = "{sid}"


def get_version():
    try:
        return (Path(__file__).resolve().parents[2] / "VERSION").read_text().strip()
    except Exception:
        return "0.0.0"


def iso_now():
    return datetime.now(timezone.utc).isoformat()


{_EMIT_TEMPLATE}


def _run(ssh, cmd: str, timeout: int = 10) -> str:
    """Execute command over SSH, return stdout."""
    try:
        _, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
        return stdout.read().decode("utf-8", errors="replace").strip()
    except Exception as exc:
        return f"ERROR: {{exc}}"


{"".join(check_fns)}

def run_checks(collection, out, attack_path_id, run_id, workload_id):
    """Run all check functions against collected data."""
    {all_checks}


def main():
    import argparse, paramiko
    p = argparse.ArgumentParser()
    p.add_argument("--host", required=True)
    p.add_argument("--user", required=True)
    p.add_argument("--password", default=None)
    p.add_argument("--key", default=None)
    p.add_argument("--out", required=True)
    p.add_argument("--attack-path-id", required=True)
    p.add_argument("--workload-id", default=None)
    p.add_argument("--run-id", default=None)
    a = p.parse_args()

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    connect_kw = {{"hostname": a.host, "username": a.user, "timeout": 15}}
    if a.key:
        connect_kw["key_filename"] = a.key
    elif a.password:
        connect_kw["password"] = a.password
    ssh.connect(**connect_kw)

    collection = {{}}
{chr(10).join(c for c in collection_cmds)}

    run_id = a.run_id or str(uuid.uuid4())
    wid = a.workload_id or a.host
    out = Path(a.out)
    run_checks(collection, out, a.attack_path_id, run_id, wid)
    ssh.close()


if __name__ == "__main__":
    main()
'''


def _generate_adapter_via_api(prompt: str, api_key: str) -> str:
    """Generate adapter code via Anthropic API."""
    import urllib.request
    payload = json.dumps({
        "model": "claude-sonnet-4-6",
        "max_tokens": 4096,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=payload,
        headers={"Content-Type": "application/json",
                 "x-api-key": api_key,
                 "anthropic-version": "2023-06-01"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        data = json.loads(r.read())
    raw = "".join(b.get("text","") for b in data.get("content",[]) if b.get("type")=="text")
    raw = re.sub(r'^```python\s*', '', raw)
    raw = re.sub(r'^```\s*', '', raw)
    raw = re.sub(r'\s*```$', '', raw).strip()
    return raw
