#!/usr/bin/env python3
"""
adapter: web_collect
Auto-generated by skg.forge. Review collection commands and check functions.
Generated: 2026-03-16T19:34:20.923368+00:00
"""
import json, uuid, re
from pathlib import Path
from datetime import datetime, timezone

TOOLCHAIN = "skg-web-toolchain"
SOURCE_ID = "adapter.web_collect"


def get_version():
    try:
        return (Path(__file__).resolve().parents[2] / "VERSION").read_text().strip()
    except Exception:
        return "0.0.0"


def iso_now():
    return datetime.now(timezone.utc).isoformat()


def emit(out_path, wicket_id, status, evidence_rank,
         evidence_source_kind, pointer, confidence,
         attack_path_id, run_id, workload_id, extra_payload=None):
    """Append one obs.attack.precondition event to NDJSON file."""
    from datetime import datetime, timezone
    import json, uuid
    now = datetime.now(timezone.utc).isoformat()
    event = {
        "id": str(uuid.uuid4()), "ts": now,
        "type": "obs.attack.precondition",
        "source": {"source_id": SOURCE_ID, "toolchain": TOOLCHAIN,
                   "version": get_version()},
        "payload": {"wicket_id": wicket_id, "status": status,
                    "attack_path_id": attack_path_id, "run_id": run_id,
                    "workload_id": workload_id, **(extra_payload or {})},
        "provenance": {"evidence_rank": evidence_rank,
                       "evidence": {"source_kind": evidence_source_kind,
                                    "pointer": pointer,
                                    "collected_at": now,
                                    "confidence": confidence}},
    }
    with open(out_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(event) + "\n")



def _run(ssh, cmd: str, timeout: int = 10) -> str:
    """Execute command over SSH, return stdout."""
    try:
        _, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
        return stdout.read().decode("utf-8", errors="replace").strip()
    except Exception as exc:
        return f"ERROR: {exc}"



def _parse_apache_version(version_str: str):
    """Return (major, minor, patch) tuple from 'Apache/2.x.y ...' or None."""
    m = re.search(r"Apache/(\d+)\.(\d+)\.(\d+)", version_str or "")
    if m:
        return tuple(int(x) for x in m.groups())
    return None


def _parse_apr_version(version_str: str):
    """Return (major, minor, patch) from 'APR 1.x.y' or dpkg '1:1.x.y-...' or None."""
    m = re.search(r"(\d+)\.(\d+)\.(\d+)", version_str or "")
    if m:
        return tuple(int(x) for x in m.groups())
    return None


def check_w_01(collection, out, attack_path_id, run_id, workload_id):
    """W-01: Target is reachable — SSH connection itself is proof."""
    # If we reached this function, SSH connected successfully → target is reachable.
    http_banner = collection.get("http_service_banner", "")
    has_http = bool(http_banner and not http_banner.startswith("ERROR"))
    status = "realized"  # SSH connection is direct reachability evidence
    detail = f"SSH connected; http_banner={'present' if has_http else 'absent'}"
    emit(out, "W-01", status,
         evidence_rank=1, evidence_source_kind="ssh_collection",
         pointer="SSH connection success implies network reachability",
         confidence=0.95,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": detail})


def check_w_02(collection, out, attack_path_id, run_id, workload_id):
    """W-02: HTTP service is exposed and responding."""
    http_banner = collection.get("http_service_banner", "")
    # HTTP response codes (200, 301, 302, 401, 403, 404, 500) all confirm service is up
    has_http = bool(http_banner and not http_banner.startswith("ERROR") and (
        "HTTP/" in http_banner or "Server:" in http_banner
    ))
    status    = "realized" if has_http else "unknown"
    detail    = (http_banner[:200] if http_banner else "not collected")
    emit(out, "W-02", status,
         evidence_rank=2, evidence_source_kind="ssh_collection",
         pointer="HTTP banner grab via localhost curl",
         confidence=0.90 if has_http else 0.5,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": detail})


def check_w_03(collection, out, attack_path_id, run_id, workload_id):
    """W-03: CVE-2007-4723 — Apache < 2.2.6 mod_proxy ScriptAlias bypass."""
    ver_str = collection.get("apache_version", "")
    ver     = _parse_apache_version(ver_str)
    if ver is None:
        status, confidence = "unknown", 0.5
        detail = f"apache_version not parsed: {ver_str[:100]}"
    elif ver < (2, 2, 6):
        status, confidence = "realized", 0.90
        detail = f"Apache {'.'.join(str(x) for x in ver)} < 2.2.6 (CVE-2007-4723)"
    else:
        status, confidence = "blocked", 0.90
        detail = f"Apache {'.'.join(str(x) for x in ver)} >= 2.2.6 — patched"
    emit(out, "W-03", status,
         evidence_rank=3, evidence_source_kind="ssh_collection",
         pointer="apache2 -v / httpd -v version check",
         confidence=confidence,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": detail, "apache_version": ver_str[:100]})


def check_w_04(collection, out, attack_path_id, run_id, workload_id):
    """W-04: CVE-2009-1955 — APR < 1.3.3 expat XML parser DoS."""
    apr_str = collection.get("apr_version", "")
    ver     = _parse_apr_version(apr_str)
    if ver is None:
        status, confidence = "unknown", 0.5
        detail = f"APR version not parsed: {apr_str[:100]}"
    elif ver < (1, 3, 3):
        status, confidence = "realized", 0.85
        detail = f"APR {'.'.join(str(x) for x in ver)} < 1.3.3 (CVE-2009-1955)"
    else:
        status, confidence = "blocked", 0.85
        detail = f"APR {'.'.join(str(x) for x in ver)} >= 1.3.3 — patched"
    emit(out, "W-04", status,
         evidence_rank=3, evidence_source_kind="ssh_collection",
         pointer="apr-1-config --version / dpkg -l libapr1",
         confidence=confidence,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": detail, "apr_version": apr_str[:100]})


def check_w_05(collection, out, attack_path_id, run_id, workload_id):
    """W-05: CVE-2009-2699 — APR Solaris pollset event-port DoS (Solaris only)."""
    os_info = collection.get("os_release", "")
    apr_str = collection.get("apr_version", "")
    # CVE-2009-2699 is Solaris-specific (Event Port backend)
    is_solaris = "solaris" in os_info.lower() or "sunos" in os_info.lower()
    if not is_solaris:
        status, confidence = "blocked", 0.95
        detail = f"Not Solaris (os_release={os_info[:60]}); CVE-2009-2699 not applicable"
    else:
        ver = _parse_apr_version(apr_str)
        if ver is None:
            status, confidence = "unknown", 0.5
            detail = f"Solaris detected but APR version unknown: {apr_str[:60]}"
        elif ver < (1, 3, 3):
            status, confidence = "realized", 0.85
            detail = f"Solaris + APR {'.'.join(str(x) for x in ver)} < 1.3.3 (CVE-2009-2699)"
        else:
            status, confidence = "blocked", 0.85
            detail = f"Solaris but APR {'.'.join(str(x) for x in ver)} >= 1.3.3 — patched"
    emit(out, "W-05", status,
         evidence_rank=3, evidence_source_kind="ssh_collection",
         pointer="uname -s / os_release check for Solaris + APR version",
         confidence=confidence,
         attack_path_id=attack_path_id, run_id=run_id, workload_id=workload_id,
         extra_payload={"detail": detail})


def run_checks(collection, out, attack_path_id, run_id, workload_id):
    """Run all check functions against collected data."""
    check_w_01(collection, out, attack_path_id, run_id, workload_id)
    check_w_02(collection, out, attack_path_id, run_id, workload_id)
    check_w_03(collection, out, attack_path_id, run_id, workload_id)
    check_w_04(collection, out, attack_path_id, run_id, workload_id)
    check_w_05(collection, out, attack_path_id, run_id, workload_id)


def main():
    import argparse, paramiko
    p = argparse.ArgumentParser()
    p.add_argument("--host", required=True)
    p.add_argument("--user", required=True)
    p.add_argument("--password", default=None)
    p.add_argument("--key", default=None)
    p.add_argument("--out", required=True)
    p.add_argument("--attack-path-id", required=True)
    p.add_argument("--workload-id", default=None)
    p.add_argument("--run-id", default=None)
    a = p.parse_args()

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    connect_kw = {"hostname": a.host, "username": a.user, "timeout": 15}
    if a.key:
        connect_kw["key_filename"] = a.key
    elif a.password:
        connect_kw["password"] = a.password
    ssh.connect(**connect_kw)

    collection = {}
    collection["http_service_banner"] = _run(
        ssh, "curl -s --max-time 5 -I http://127.0.0.1/ 2>&1 | head -8 || echo 'no_curl'"
    )
    collection["apache_version"] = _run(
        ssh, "apache2 -v 2>/dev/null || httpd -v 2>/dev/null || apache2ctl -v 2>/dev/null || echo 'not_found'"
    )
    collection["apr_version"] = _run(
        ssh, "apr-1-config --version 2>/dev/null || "
             "dpkg -l libapr1 2>/dev/null | awk '/^ii/{print $3}' || "
             "rpm -q apr --queryformat '%{VERSION}' 2>/dev/null || echo 'not_found'"
    )
    collection["os_release"] = _run(ssh, "uname -s -r 2>/dev/null || echo 'unknown'")

    run_id = a.run_id or str(uuid.uuid4())
    wid = a.workload_id or a.host
    out = Path(a.out)
    run_checks(collection, out, a.attack_path_id, run_id, wid)
    ssh.close()


if __name__ == "__main__":
    main()
